//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quierobesarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public string device { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string method { get; set; }
        public string user { get; set; }
        public string status { get; set; }
    }
}
