//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quierobesarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class wedding_image
    {
        public decimal id { get; set; }
        public string wedding_id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public string user_created { get; set; }
    
        public virtual wedding wedding { get; set; }
    }
}
