//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quierobesarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class wedding
    {
        public wedding()
        {
            this.wedding_image = new HashSet<wedding_image>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string path { get; set; }
        public byte[] qrcode { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<wedding_image> wedding_image { get; set; }
    }
}
